export type VenezuelaPostalZone = {
  postalCode: string;
  zone: string;
  state: string;
};

export const venezuelaPostalZones = [
  { postalCode: "1000", zone: "Caracas - Zona Metropolitana", state: "Distrito Capital" },
  { postalCode: "1010", zone: "Caracas - Catedral", state: "Distrito Capital" },
  { postalCode: "1011", zone: "Caracas - San Bernardino", state: "Distrito Capital" },
  { postalCode: "1012", zone: "Caracas - La Candelaria", state: "Distrito Capital" },
  { postalCode: "1014", zone: "Caracas - El Recreo", state: "Distrito Capital" },
  { postalCode: "1015", zone: "Caracas - San José", state: "Distrito Capital" },
  { postalCode: "1020", zone: "Caracas - Antímano", state: "Distrito Capital" },
  { postalCode: "1020", zone: "Caracas - El Paraíso", state: "Distrito Capital" },
  { postalCode: "1020", zone: "Caracas - La Vega", state: "Distrito Capital" },
  { postalCode: "1020", zone: "Caracas - Montalbán", state: "Distrito Capital" },
  { postalCode: "1030", zone: "Caracas - Caricuao", state: "Distrito Capital" },
  { postalCode: "1030", zone: "Caracas - Macarao", state: "Distrito Capital" },
  { postalCode: "1040", zone: "Caracas - San Agustín", state: "Distrito Capital" },
  { postalCode: "1050", zone: "Caracas - Chacao", state: "Miranda" },
  { postalCode: "1060", zone: "Caracas - Baruta", state: "Miranda" },
  { postalCode: "1060", zone: "Caracas - El Hatillo", state: "Miranda" },
  { postalCode: "1070", zone: "Caracas - Petare", state: "Miranda" },
  { postalCode: "1071", zone: "Caracas - Los Dos Caminos", state: "Miranda" },
  { postalCode: "1073", zone: "Caracas - La Urbina", state: "Miranda" },
  { postalCode: "1080", zone: "Caracas - Prados del Este", state: "Miranda" },
  { postalCode: "1083", zone: "Caracas - Las Minas de Baruta", state: "Miranda" },
  { postalCode: "1090", zone: "Caracas - El Valle", state: "Distrito Capital" },
  { postalCode: "1100", zone: "La Guaira", state: "La Guaira" },
  { postalCode: "1160", zone: "Catia La Mar", state: "La Guaira" },
  { postalCode: "1162", zone: "Maiquetía", state: "La Guaira" },
  { postalCode: "1164", zone: "Macuto", state: "La Guaira" },
  { postalCode: "1165", zone: "Caraballeda", state: "La Guaira" },
  { postalCode: "1201", zone: "Los Teques", state: "Miranda" },
  { postalCode: "1203", zone: "San Antonio de los Altos", state: "Miranda" },
  { postalCode: "1204", zone: "Carrizal", state: "Miranda" },
  { postalCode: "1210", zone: "Guarenas", state: "Miranda" },
  { postalCode: "1220", zone: "Guatire", state: "Miranda" },
  { postalCode: "1232", zone: "Charallave", state: "Miranda" },
  { postalCode: "1212", zone: "Ocumare del Tuy", state: "Miranda" },
  { postalCode: "1246", zone: "Cúa", state: "Miranda" },
  { postalCode: "1241", zone: "Santa Teresa del Tuy", state: "Miranda" },
  { postalCode: "1244", zone: "Santa Lucía", state: "Miranda" },
  { postalCode: "1238", zone: "Higuerote", state: "Miranda" },
  { postalCode: "1231", zone: "Río Chico", state: "Miranda" },
  { postalCode: "2001", zone: "Valencia", state: "Carabobo" },
  { postalCode: "2003", zone: "Naguanagua", state: "Carabobo" },
  { postalCode: "2005", zone: "San Diego", state: "Carabobo" },
  { postalCode: "2010", zone: "Guacara", state: "Carabobo" },
  { postalCode: "2011", zone: "Mariara", state: "Carabobo" },
  { postalCode: "2015", zone: "Tocuyito", state: "Carabobo" },
  { postalCode: "2035", zone: "Puerto Cabello", state: "Carabobo" },
  { postalCode: "2050", zone: "Bejuma", state: "Carabobo" },
  { postalCode: "2101", zone: "Maracay", state: "Aragua" },
  { postalCode: "2103", zone: "Turmero", state: "Aragua" },
  { postalCode: "2115", zone: "La Victoria", state: "Aragua" },
  { postalCode: "2117", zone: "Cagua", state: "Aragua" },
  { postalCode: "2118", zone: "Santa Cruz de Aragua", state: "Aragua" },
  { postalCode: "2122", zone: "Villa de Cura", state: "Aragua" },
  { postalCode: "2126", zone: "El Consejo", state: "Aragua" },
  { postalCode: "2330", zone: "San Juan de los Morros", state: "Guárico" },
  { postalCode: "2301", zone: "Calabozo", state: "Guárico" },
  { postalCode: "2320", zone: "Valle de la Pascua", state: "Guárico" },
  { postalCode: "2350", zone: "Altagracia de Orituco", state: "Guárico" },
  { postalCode: "3001", zone: "Barquisimeto", state: "Lara" },
  { postalCode: "3015", zone: "Cabudare", state: "Lara" },
  { postalCode: "3023", zone: "Carora", state: "Lara" },
  { postalCode: "3031", zone: "Quíbor", state: "Lara" },
  { postalCode: "3050", zone: "El Tocuyo", state: "Lara" },
  { postalCode: "3201", zone: "San Felipe", state: "Yaracuy" },
  { postalCode: "3202", zone: "Yaritagua", state: "Yaracuy" },
  { postalCode: "3210", zone: "Chivacoa", state: "Yaracuy" },
  { postalCode: "3221", zone: "Nirgua", state: "Yaracuy" },
  { postalCode: "3301", zone: "Acarigua", state: "Portuguesa" },
  { postalCode: "3302", zone: "Araure", state: "Portuguesa" },
  { postalCode: "3310", zone: "Guanare", state: "Portuguesa" },
  { postalCode: "3350", zone: "Ospino", state: "Portuguesa" },
  { postalCode: "4001", zone: "Maracaibo", state: "Zulia" },
  { postalCode: "4013", zone: "Cabimas", state: "Zulia" },
  { postalCode: "4014", zone: "Ciudad Ojeda", state: "Zulia" },
  { postalCode: "4015", zone: "Lagunillas", state: "Zulia" },
  { postalCode: "4020", zone: "Santa Rita", state: "Zulia" },
  { postalCode: "4032", zone: "Machiques", state: "Zulia" },
  { postalCode: "4044", zone: "Villa del Rosario", state: "Zulia" },
  { postalCode: "5145", zone: "Mérida", state: "Mérida" },
  { postalCode: "5101", zone: "Ejido", state: "Mérida" },
  { postalCode: "5111", zone: "El Vigía", state: "Mérida" },
  { postalCode: "5127", zone: "Tovar", state: "Mérida" },
  { postalCode: "5001", zone: "San Cristóbal", state: "Táchira" },
  { postalCode: "5002", zone: "Táriba", state: "Táchira" },
  { postalCode: "5010", zone: "Rubio", state: "Táchira" },
  { postalCode: "5020", zone: "La Fría", state: "Táchira" },
  { postalCode: "5030", zone: "Colón", state: "Táchira" },
  { postalCode: "5201", zone: "Barinas", state: "Barinas" },
  { postalCode: "5210", zone: "Socopó", state: "Barinas" },
  { postalCode: "5221", zone: "Santa Bárbara de Barinas", state: "Barinas" },
  { postalCode: "5250", zone: "Sabaneta", state: "Barinas" },
  { postalCode: "6001", zone: "Barcelona", state: "Anzoátegui" },
  { postalCode: "6016", zone: "Puerto La Cruz", state: "Anzoátegui" },
  { postalCode: "6023", zone: "Lechería", state: "Anzoátegui" },
  { postalCode: "6022", zone: "Guanta", state: "Anzoátegui" },
  { postalCode: "6050", zone: "El Tigre", state: "Anzoátegui" },
  { postalCode: "6007", zone: "Anaco", state: "Anzoátegui" },
  { postalCode: "6150", zone: "Cumaná", state: "Sucre" },
  { postalCode: "6152", zone: "Carúpano", state: "Sucre" },
  { postalCode: "6164", zone: "Güiria", state: "Sucre" },
  { postalCode: "6110", zone: "Cariaco", state: "Sucre" },
  { postalCode: "6201", zone: "Maturín", state: "Monagas" },
  { postalCode: "6206", zone: "Punta de Mata", state: "Monagas" },
  { postalCode: "6210", zone: "Temblador", state: "Monagas" },
  { postalCode: "6301", zone: "Porlamar", state: "Nueva Esparta" },
  { postalCode: "6311", zone: "La Asunción", state: "Nueva Esparta" },
  { postalCode: "6304", zone: "Pampatar", state: "Nueva Esparta" },
  { postalCode: "6316", zone: "Juan Griego", state: "Nueva Esparta" },
  { postalCode: "7001", zone: "San Fernando de Apure", state: "Apure" },
  { postalCode: "7011", zone: "Achaguas", state: "Apure" },
  { postalCode: "7007", zone: "Biruaca", state: "Apure" },
  { postalCode: "5063", zone: "Guasdualito", state: "Apure" },
  { postalCode: "8001", zone: "Ciudad Bolívar", state: "Bolívar" },
  { postalCode: "8050", zone: "Ciudad Guayana - Puerto Ordaz", state: "Bolívar" },
  { postalCode: "8051", zone: "Ciudad Guayana - San Félix", state: "Bolívar" },
  { postalCode: "8052", zone: "Upata", state: "Bolívar" },
  { postalCode: "8057", zone: "Tumeremo", state: "Bolívar" },
  { postalCode: "8011", zone: "Caicara del Orinoco", state: "Bolívar" },
  { postalCode: "7101", zone: "Tucupita", state: "Delta Amacuro" },
  { postalCode: "6401", zone: "Puerto Ayacucho", state: "Amazonas" },
  { postalCode: "4101", zone: "Coro", state: "Falcón" },
  { postalCode: "4102", zone: "La Vela de Coro", state: "Falcón" },
  { postalCode: "4122", zone: "Punto Fijo", state: "Falcón" },
  { postalCode: "4150", zone: "Chichiriviche", state: "Falcón" },
  { postalCode: "3110", zone: "Valera", state: "Trujillo" },
  { postalCode: "3150", zone: "Trujillo", state: "Trujillo" },
  { postalCode: "3105", zone: "Boconó", state: "Trujillo" },
] as const satisfies readonly VenezuelaPostalZone[];

export const venezuelaLocationOptions = venezuelaPostalZones.map(
  ({ postalCode, zone, state }) => `${postalCode} - ${zone}, ${state}`,
);

const venezuelaLocationOptionSet = new Set(venezuelaLocationOptions);

export function isVenezuelaLocationOption(value: string) {
  return venezuelaLocationOptionSet.has(value.trim());
}
